# Permalinks
permalink:        pretty

# Settings
markdown:         kramdown
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             Beautiful Open
url:              http://michelthierry.org/beautiful-open
description:      "Handsome sites for open source"
